### ISSUE TITLE
model init problem?

### ISSUE THREAD

**Issue by xdlxl** [xlvector/sw2v#1]
int model_size = nword \* nhidden_;
  vectorps::Key keys(nword, 0);
  vector<float> vals(nword, 0);
  for(int i = 0; i < nword**(maybe change to model_size)**; i++) {
    keys[i] = rand() % model_size;
    vals[i] = (RAND01() - 0.5) / sqrt(float(nhidden_) + 1.0);
}

**Comment by xlvector** [comment]
3x, you are right. You can submit an PR.
